pool:
  name: Neurapulse

trigger: none
pr: none

resources:
  pipelines:
    - pipeline: CI
      source: \Help2\Help2 - CI
      trigger:
        branches:
          include:
            - main

variables:
  - template: vars.yml

steps:
  - checkout: self
    fetchDepth: 0
  - script: |
      set -e
      git config user.email "docs-bot@impirica.com"
      git config user.name "Impirica Docs Bot"
      git subtree split -P help2 -b help2-export
      git remote add github https://$(GITHUB_TOKEN_STAGE)@github.com/dscott004/stage-help.git
      git push -f github refs/heads/help2-export:refs/heads/main
    displayName: Mirror /help2 to GitHub (stage)
