trigger:
  branches:
    include:
      - main
  paths:
    include:
      - help2/**/*
pr: none

pool:
  name: Neurapulse

variables:
  - template: vars.yml

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
      checkLatest: true
    displayName: Use Node.js 20.x
  - bash: npm i -g mint
    displayName: Install Mintlify CLI
  - bash: |
      set -euo pipefail
      # Workaround for environments without /dev/stderr: capture to a temp file and grep
      TMP_LOG=$(mktemp)
      mint broken-links | tee "$TMP_LOG"
      grep -qi 'success no broken links found' "$TMP_LOG"
    displayName: Check broken links
    workingDirectory: $(working_directory)
  - bash: |
      set -e
      if [ -d "api-reference" ]; then
        files=$(find api-reference -type f \( -name '*.yaml' -o -name '*.yml' -o -name '*.json' \))
        if [ -z "$files" ]; then
          echo "No OpenAPI specs found"
        else
          for f in $files; do
            echo "Checking $f"
            mint openapi-check "$f"
          done
        fi
      else
        echo "No api-reference directory"
      fi
    displayName: Validate OpenAPI specs
    workingDirectory: $(working_directory)
